### ISSUE TITLE
Shop item loading doesn't work when inventory slots are non-sequential 

### ISSUE THREAD

**Issue by Parsonswy** [peacefulcraft-network/Tarje#11]
The following should be considered a valid configuration and slot 1 would be left empty. Currently, the config processor loads the item in slot 0, doesn't see a slot one, and stops. The items in slots 2 and 3 are never loaded.
```yaml
'0':
  item: CHICKEN
  buy: 40.0
  sell: 10.0
'2':
  item: RABBIT
  buy: 40.0
  sell: 10.0
'3':
  item: MUTTON
  buy: 40.0
  sell: 10.0
```
